# Generated by Django 3.0.3 on 2020-02-28 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ед.изм.', max_length=20, verbose_name='Наименование ед. изм.')),
                ('short', models.CharField(default='ед.изм.', max_length=10, verbose_name='Краткое наименование')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(5, 'Менеджер сервиса'), (4, 'Продавец'), (3, 'Транспортник'), (2, 'Платный пользователь'), (1, 'Бесплатный пользователь')], default=5, verbose_name='Тип')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Телефон')),
                ('company_name', models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='Юридический адрес')),
                ('bin', models.IntegerField(blank=True, default=None, null=True, verbose_name='БИН')),
                ('bank_account', models.CharField(blank=True, default=None, max_length=1500, null=True, verbose_name='Банковские реквизиты')),
                ('tg_id', models.IntegerField(blank=True, default=None, null=True, verbose_name='Телеграм-идентификатор пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Наименование')),
                ('price', models.FloatField(default='0.0', verbose_name='Цена, тенге')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='webpanel.ProductCategory', verbose_name='Категория')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpanel.ProductUnitType', verbose_name='Ед. изм.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PriceLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='pricelists')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pricelists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
