# Generated by Django 3.0.3 on 2020-02-28 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tg_id',
            new_name='telegram_id',
        ),
    ]
