# Generated by Django 3.0.3 on 2020-03-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0002_auto_20200228_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(max_length=500, verbose_name='Наименование'),
        ),
    ]
