# Generated by Django 3.0.3 on 2020-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0003_auto_20200301_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(db_index=True, verbose_name='Наименование'),
        ),
    ]
