# Generated by Django 3.0.3 on 2020-03-01 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpanel', '0004_auto_20200301_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelists',
            options={'verbose_name': 'Загруженный прайс-лист', 'verbose_name_plural': 'Загруженные прайс-листы'},
        ),
        migrations.AlterField(
            model_name='pricelists',
            name='file_name',
            field=models.FileField(upload_to='pricelists', verbose_name='Файл прайса'),
        ),
        migrations.AlterField(
            model_name='pricelists',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='pricelists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_pricelists', to=settings.AUTH_USER_MODEL, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_products', to='webpanel.ProductCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена, тенге'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='webpanel.ProductUnitType', verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
