# Generated by Django 3.0.3 on 2020-03-01 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpanel', '0005_auto_20200301_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Время создания заявки')),
                ('bill_date', models.DateTimeField(default=None, verbose_name='Время выставления счёта')),
                ('delivery_date', models.DateTimeField(default=None, verbose_name='Время принятия заявки транспортником')),
                ('order_number', models.IntegerField(default=0, verbose_name='Номер заказа')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_orders', to='webpanel.Product', verbose_name='Заказанный товар')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, заказавший товар')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
