# Generated by Django 3.0.3 on 2020-03-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0008_auto_20200301_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
