# Generated by Django 3.0.3 on 2020-03-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0009_auto_20200301_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=0, null=True, verbose_name='Статус заказа'),
        ),
    ]
