# Generated by Django 3.0.3 on 2020-03-02 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpanel', '0010_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Номер заказа')),
                ('file_name', models.FileField(upload_to='sellers_bills', verbose_name='Файл счёта')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order_sum', models.FloatField(verbose_name='Сумма, тенге')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_seller', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_user', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Загруженный cчёт на оплату товара',
                'verbose_name_plural': 'Загруженные счета на оплату товара',
            },
        ),
    ]
