# Generated by Django 3.0.3 on 2020-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0012_sellerbill_reseived_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_count',
            field=models.FloatField(default=0.0, verbose_name='Количество заказанного товара'),
        ),
    ]
