# Generated by Django 3.0.3 on 2020-03-17 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0014_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='reseived_flag',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Отметка о получении счёта покупателем'),
        ),
    ]
