# Generated by Django 3.0.3 on 2020-03-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpanel', '0015_delivery_reseived_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunittype',
            name='name',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='Наименование ед. изм.'),
        ),
        migrations.AlterField(
            model_name='productunittype',
            name='short',
            field=models.CharField(default=None, max_length=10, null=True, verbose_name='Краткое наименование'),
        ),
    ]
