# Generated by Django 3.0.3 on 2020-03-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpanel', '0016_auto_20200318_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=None, null=True, verbose_name='Начало платного периода')),
                ('date_end', models.DateTimeField(default=None, null=True, verbose_name='Окончание периода')),
                ('amount', models.FloatField(default=0.0, verbose_name='Оплаченная сумма')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_bill', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_bill', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оплаченный аккаунт',
                'verbose_name_plural': 'оплаченные аккаунты',
            },
        ),
    ]
