# Generated by Django 3.0.3 on 2020-03-17 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=None, null=True, verbose_name='Время запроса')),
                ('chat_id', models.IntegerField(default=0, null=True, verbose_name='Идентификатор чата в ТГ')),
                ('message', models.TextField(default=None, null=True, verbose_name='Текст запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос из Телеграма',
                'verbose_name_plural': 'Запросы из Телеграма',
            },
        ),
    ]
