# Generated by Django 3.0.3 on 2020-03-17 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0002_auto_20200317_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время запроса'),
            preserve_default=False,
        ),
    ]
