# Generated by Django 3.0.3 on 2020-03-19 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram_bot', '0004_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='actor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='manager_message', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='reseived_flag',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Отметка о получении счёта покупателем'),
        ),
    ]
